auth_enabled: false

server:
  http_listen_port: 3100
  http_tls_config: &tls_server_config

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  wal:
    enabled: true
    dir: /tmp/loki/wal
  lifecycler:
    address: localhost
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 15m
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/boltdb-shipper-active
    cache_location: /tmp/loki/boltdb-shipper-cache
    resync_interval: 5m
  filesystem:
    directory: /tmp/loki/chunks

compactor:
  working_directory: /path/to/loki/compactor

limits_config:
  ingestion_rate_mb: 10   # Meningkatkan batas laju menjadi 10 MB/s
  ingestion_burst_size_mb: 20  # Meningkatkan ukuran burst menjadi 20 MB
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
